language: python

matrix:
  include:
    - python: 2.6
      env: TOXENV=py26
    - python: 2.7
      env: TOXENV=py27
    - python: pypy
      env: TOXENV=pypy

install:
  - "pip install tox"
script: "tox -- -rs"
